name: Build docker containers

on: [push]

jobs:
  build-and-push-containers:
    env:
      DOCKER_USERNAME: mdiakhate12
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push publisher container
      run: |
        docker build -t $DOCKER_USERNAME/rabbitmq-publisher publisher/
        docker push $DOCKER_USERNAME/rabbitmq-publisher
    - name: Build  and push subscriber container
      run: |
        docker build -t $DOCKER_USERNAME/rabbitmq-subscriber subscriber/
        docker push $DOCKER_USERNAME/rabbitmq-subscriber

